defaultEntryPoints = ["http"]

[api]
  dashboard = true
  #insecure = true
  debug = true

[metrics]
  [metrics.prometheus]
    addEntryPointsLabels = true
    addServicesLabels = true
    entryPoint = "http"

[entryPoints]
  [entryPoints.http]
    address = ":8888"

  [entryPoints.api]
    address = ":8080"

[providers]
  [providers.file]
    filename = "traefik-dynamic.toml"
