[http]
  # Add the router
  [http.routers.my-router]
    entryPoints = ["http"]
    service = "service-http"
    rule = "PathPrefix(`/`)"
  
  # Secure api
  [http.routers.my-api]
    entryPoints = ["api"]
    rule = "(PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
    service = "api@internal"
    middlewares = ["auth"]

  # Middleware for secure api
  [http.middlewares]
    [http.middlewares.auth.basicAuth]
    users = [
      "test:$apr1$iOcqZeiB$rn/81r4ckD1XlPuFgOtBn/",
      ]

  # Add the service
  [http.services]
    [http.services.service-http.loadBalancer]
      [[http.services.service-http.loadBalancer.servers]]
        url = "http://127.0.0.1:81"
      [[http.services.service-http.loadBalancer.servers]]
        url = "http://127.0.0.1:82"
