defaultEntryPoints = ["http", "https"]

# enable dashboard
[api]
    dashboard = true
    #insecure = true

# create entrypoint
[entryPoints]
    [entryPoints.http]
        address = ":80"
        
        # create redirect entrypoint 80 to 443
        [entryPoints.http.http.redirections]
            [entryPoints.http.http.redirections.entryPoint]
                to = "https"
                scheme = "https"
                permanent = true

    [entryPoints.https]
        address = ":443"

    [entryPoints.api]
        address = ":8080"

# enable prometheus metrics
[metrics]
    [metrics.prometheus]
        addEntryPointsLabels = true
        addServicesLabels = true
        entryPoint = "http"

# user file provider
[providers]
    [providers.file]    
        filename = "traefik-dynamic.toml"
    [providers.docker]
        endpoint = "unix:///var/run/docker.sock"
